name: test-harness-acapy-anoncreds
# RUNSET_NAME: "ACA-PY to ACA-Py Anoncreds"
# Scope: AIP 2.0
# Exceptions: None
# 
# Summary
#
# This runset uses the current main branch of ACA-Py for all of the agents. The runset runs all of the tests in the suite
# that are expected to pass given the current state of ACA-Py support for AIP 1 and 2. This runset specifically targets anoncreds 
# support in ACA-Py.
#
# Current
# 
# All of the tests being executed in this runset are passing.
# 
# *Status Note Updated: 2025.03.13*
#
# End
on:
  workflow_dispatch:
defaults:
  run:
    shell: bash
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      LEDGER_URL_CONFIG: "http://localhost:9000"
      TAILS_SERVER_URL_CONFIG: "http://localhost:6543"
    steps:
      - name: checkout-test-harness
        uses: actions/checkout@v4
        with:
          path: test-harness
      - name: run-von-network
        uses: ./test-harness/actions/run-von-network
      - name: run-indy-tails-server
        uses: ./test-harness/actions/run-indy-tails-server
      - name: run-test-harness-wo-reports
        id: run_test_harness
        uses: ./test-harness/actions/run-test-harness-wo-reports
        with:
          BUILD_AGENTS: "-a acapy-main"
          TEST_AGENTS: "-d acapy-main"
          TEST_SCOPE: "-t @AcceptanceTest -t ~@wip -t ~@T004-RFC0211 -t ~@DidMethod_orb -t ~@Transport_NoHttpOutbound -t ~@Indy -t ~@CredFormat_Indy"
          REPORT_PROJECT: acapy
        env:
          BACKCHANNEL_EXTRA_acapy_main: "{\"wallet-type\":\"askar-anoncreds\"}"
      - name: run-send-gen-test-results-secure
        if: ${{ steps.run_test_harness.conclusion == 'success' }}
        uses: ./test-harness/actions/run-send-gen-test-results-secure
        with:
          REPORT_PROJECT: acapy-anoncreds
          ADMIN_USER: ${{ secrets.AllureAdminUser }}
          ADMIN_PW: ${{ secrets.AllureAdminPW }}
