name: test-harness-acapy-anoncreds-credo
# RUNSET_NAME: "ACA-PY/AnonCreds to Credo"
# Scope: AnonCreds
#
# Summary
#
# This runset uses the current main branch of ACA-Py for all of the agents except Bob (holder),
# which uses the master branch of Credo TS. The runset covers a small number of credential
# issue and revocation scenarios for AnonCreds credentials.
#
# Current
#
# Initial version created.
#
# *Status Note Updated: 2025.03.20*
#
# End
on:
  workflow_dispatch:
defaults:
  run:
    shell: bash
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      LEDGER_URL_CONFIG: "http://localhost:9000"
      TAILS_SERVER_URL_CONFIG: "http://localhost:6543"
      START_TIMEOUT: 120
    steps:
      - name: checkout-test-harness
        uses: actions/checkout@v4
        with:
          path: test-harness
      - name: run-von-network
        uses: ./test-harness/actions/run-von-network
      - name: run-indy-tails-server
        uses: ./test-harness/actions/run-indy-tails-server
      - name: run-test-harness-wo-reports
        id: run_test_harness
        uses: ./test-harness/actions/run-test-harness-wo-reports
        with:
          BUILD_AGENTS: "-a acapy-main -a credo"
          TEST_AGENTS: "-d acapy-main -b credo"
          TEST_SCOPE: "-t @AcceptanceTest -t @AIP10,@RFC0441,@RFC0211,@T001-RFC0453,@T001-RFC0454b -t ~@wip -t ~@DIDExchangeConnection -t ~@T004-RFC0211 -t ~@QualifiedDIDs -t ~@T001-RFC0183 -t @Anoncreds"
          REPORT_PROJECT: acapy-anoncreds-credo
        env:
          BACKCHANNEL_EXTRA_acapy_main: "{\"wallet-type\":\"askar-anoncreds\"}"
      - name: run-send-gen-test-results-secure
        if: ${{ steps.run_test_harness.conclusion == 'success' }}
        uses: ./test-harness/actions/run-send-gen-test-results-secure
        with:
          REPORT_PROJECT: acapy-anoncreds-credo
          ADMIN_USER: ${{ secrets.AllureAdminUser }}
          ADMIN_PW: ${{ secrets.AllureAdminPW }}
